{"name": "test_case02", "status": "failed", "statusDetails": {"message": "Failed: [XPASS(strict)] 预期失败，执行成功", "trace": "[XPASS(strict)] 预期失败，执行成功"}, "description": "02预期失败，但实际结果却执行成功了", "start": 1588051809734, "stop": 1588051809734, "uuid": "c4bef737-5918-474d-9a33-40fe326d2c75", "historyId": "cb8dac564d896999012e51f56e115f1c", "testCaseId": "1f3062cf45b175f9f4ec95c91ec54d83", "fullName": "test_xfail.TestCase#test_case02", "labels": [{"name": "suite", "value": "test_xfail"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "PC-BFD8TY2"}, {"name": "thread", "value": "1676-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_xfail"}]}