{"name": "test_exception_value02", "status": "broken", "statusDetails": {"message": "TypeError: 传入的参数不是整数", "trace": "self = <test_leap_year.TestAssert object at 0x000001A393E89148>\n\n    def test_exception_value02(self):\n        with pytest.raises(ValueError) as excinfo:\n>           is_leap_year('yu')\n\ntest_leap_year.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nyear = 'yu'\n\n    def is_leap_year(year):\n        if isinstance(year, int) is not True:\n>           raise TypeError(\"传入的参数不是整数\")\nE           TypeError: 传入的参数不是整数\n\ntest_leap_year.py:14: TypeError"}, "start": 1588052546318, "stop": 1588052546318, "uuid": "20e03132-f837-4317-a16b-ab433c78dea9", "historyId": "f62f7230e1eb30bd22ac8d12190d118b", "testCaseId": "3746a4c7b1b4404ba147d7e67606c68b", "fullName": "test_leap_year.TestAssert#test_exception_value02", "labels": [{"name": "suite", "value": "test_leap_year"}, {"name": "subSuite", "value": "TestAssert"}, {"name": "host", "value": "PC-BFD8TY2"}, {"name": "thread", "value": "3208-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_leap_year"}]}